### ISSUE TITLE
Revoke access if user removed from the group

### ISSUE THREAD

**Issue by sirantd** [aws-samples/sso-sync-to-amazon-rds#1]
Hi,

I realise that it's just an example of how things can be automated in AWS, but by doing it, we should be aware that it will not cause additional harm to those who will use it.

As for me, we need to extend the example with the code, which will revoke access in case of the removing user from the `DBA` group or, at least, state in the Readme that removing a user from the `DBA` group will not revoke his access from the RDS MySQL.

**Comment by arachyts** [comment]
Hi! Yes, that makes sense - thank you for pointing that out. The solution now includes a new ownership model based on roles, and it will delete a user from the database if it's deleted from the SSO Identity Provider.
